package org.pine.common.criteria;

import java.util.List;

/** 
* @author  xuj: 
* @date 创建时间：2016年10月31日 上午9:55:25 
* @version 1.0 
* @parameter  
* @since  
* @return  
*/
/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table YZT_MENU
 * @mbg.generated  Sun Oct 09 14:33:48 CST 2016
 */

public class Criterion {
	private String condition;
	private Object value;
	private Object secondValue;
	private boolean noValue;
	private boolean singleValue;
	private boolean betweenValue;
	private boolean listValue;
	private String typeHandler;

	public String getCondition() {
		return condition;
	}

	public Object getValue() {
		return value;
	}

	public Object getSecondValue() {
		return secondValue;
	}

	public boolean isNoValue() {
		return noValue;
	}

	public boolean isSingleValue() {
		return singleValue;
	}

	public boolean isBetweenValue() {
		return betweenValue;
	}

	public boolean isListValue() {
		return listValue;
	}

	public String getTypeHandler() {
		return typeHandler;
	}

	public Criterion(String condition) {
		super();
		this.condition = condition;
		this.typeHandler = null;
		this.noValue = true;
	}

	public Criterion(String condition, Object value, String typeHandler) {
		super();
		this.condition = condition;
		this.value = value;
		this.typeHandler = typeHandler;
		if (value instanceof List<?>) {
			this.listValue = true;
		} else {
			this.singleValue = true;
		}
	}

	public Criterion(String condition, Object value) {
		this(condition, value, null);
	}

	public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
		super();
		this.condition = condition;
		this.value = value;
		this.secondValue = secondValue;
		this.typeHandler = typeHandler;
		this.betweenValue = true;
	}

	public Criterion(String condition, Object value, Object secondValue) {
		this(condition, value, secondValue, null);
	}
}

